### ISSUE TITLE
Remove "0:/" from URL

### ISSUE THREAD

**Issue by JustThinker1** [cheems/GDIndex#11]
Hello,

May you add an option to remove the "0:/" from the url?

The indexer is looked like that "https://ex.example.workers.dev/0:/"

Is it possible to make it "https://ex.example.workers.dev/"

Sincerely

**Comment by cheems** [comment]
This is in my todo list also. But at the moment, I'm not sure whether it can be done or not because I'm still not very comfortable with the language as well as the Google drive API. But even it is possible, I think it may need some major changes. So I'm thinking of trying it after all is added that needs minor changes. Therefore it may take some time
