### ISSUE TITLE
Folders and files with some symbols in the name breaks

### ISSUE THREAD

**Issue by Dawok** [cheems/GDIndex#9]
Might be more symbols other than #, ", ' breaking it
![miniflare](https://dubu.kim/h68vn.png)

**Comment by cheems** [comment]
Hey could you specify a little more. I think you meant that having symbols (other than the ones you mentioned) in folder/file names doesn't work. What happens when you put them in a file/folder name? the current page reloads or something else?
and could you tell me which symbols you experience the error with?

**Comment by Dawok** [comment]
https://odd-sun-08de.dawok.workers.dev/0:/ put up one with some test folders and files. Getting "Error 1101 Worker threw exception"
Apostrophe seems to be fine. But quotation marks and hashtags errors out. 
Another google drive index project had the same problem https://github.com/LeeluPradhan/G-Index/issues/10#issue-649164765

**Comment by cheems** [comment]
fixed!
